---
- name: "Extract Artifact"
  become: yes
  unarchive:
    src: files/artifact.tar.gz
    dest: ~/

- name: "start server"
  become: true
  shell: | 
    npm install
    pm2 stop default
    sudo pm2 start npm -- start


# - name: "copy artifact into the server"
#   become: true
#   copy:
#     src: files/artifact.tar.gz
#     dest: ~/

# - name: "extract zipped artifact and install dependancies"
#   become: true
#   shell: |
#     tar -xvzf ~/artifact.tar.gz

# - name: "Extract artifact to EC2"
#   unarchive:
#     src: ~/project/artifact.tar.gz
#     dest: /home/ubuntu