---
- name: "Extract Artifact"
  unarchive:
    src: ~/project/artifact.tar.gz
    dest: ~/

# - name: "install dependencies."
#   become: yes
#   apt:
#     name: ["nodejs", "npm"]
#     state: latest
#     update_cache: yes

- name: "start server"
  become: true
  shell: | 
    pm2 stop default
    pm2 start npm -- start


# - name: "copy artifact into the server"
#   become: true
#   copy:
#     src: files/artifact.tar.gz
#     dest: ~/

# - name: "extract zipped artifact and install dependancies"
#   become: true
#   shell: |
#     tar -xvzf ~/artifact.tar.gz

# - name: "Extract artifact to EC2"
#   unarchive:
#     src: ~/project/artifact.tar.gz
#     dest: /home/ubuntu